/*
 * FilterSettingsForm.java
 *
 * Created on January 20, 2007, 2:15 PM
 */

package org.jmeld.ui.settings;

/**
 *
 * @author  kees
 */
public class FilterSettingsForm extends javax.swing.JPanel
{
  
  /** Creates new form FilterSettingsForm */
  public FilterSettingsForm ()
  {
    initComponents ();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    jScrollPane2 = new javax.swing.JScrollPane();
    jMTable1 = new org.jmeld.ui.swing.table.JMTable();
    gradientLabel1 = new org.jmeld.ui.swing.GradientLabel();
    newFilterButton = new javax.swing.JButton();
    detailHeader1 = new org.jmeld.ui.swing.DetailHeader();
    deleteFilterButton = new javax.swing.JButton();
    detailHeader2 = new org.jmeld.ui.swing.DetailHeader();
    includeDefaultFilterCheckbox = new javax.swing.JCheckBox();
    newFilterRuleButton = new javax.swing.JButton();
    deleteFilterRuleButton = new javax.swing.JButton();
    filterNameLabel = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    filterRuleTable = new org.jmeld.ui.swing.table.JMTable();
    jScrollPane1 = new javax.swing.JScrollPane();
    filterTable = new org.jmeld.ui.swing.table.JMTable();

    jMTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane2.setViewportView(jMTable1);

    gradientLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    gradientLabel1.setText("Filter settings");
    gradientLabel1.setFont(new java.awt.Font("Dialog", 1, 18));

    newFilterButton.setText("New");
    newFilterButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        newFilterButtonActionPerformed(evt);
      }
    });

    detailHeader1.setText("Filters");

    deleteFilterButton.setText("Delete");

    detailHeader2.setText("Filter rules for: ");

    includeDefaultFilterCheckbox.setText("Include default filter");
    includeDefaultFilterCheckbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    includeDefaultFilterCheckbox.setMargin(new java.awt.Insets(0, 0, 0, 0));

    newFilterRuleButton.setText("New");

    deleteFilterRuleButton.setText("Delete");

    filterNameLabel.setText("FilterName");

    filterRuleTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane3.setViewportView(filterRuleTable);

    filterTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(filterTable);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(gradientLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(detailHeader2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(filterNameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
            .addContainerGap())
          .add(layout.createSequentialGroup()
            .add(12, 12, 12)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                  .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                  .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                  .add(newFilterRuleButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .add(deleteFilterRuleButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .add(deleteFilterButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .add(newFilterButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
              .add(layout.createSequentialGroup()
                .add(includeDefaultFilterCheckbox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())))
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(detailHeader1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(gradientLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(detailHeader1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(newFilterButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(deleteFilterButton))
          .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(detailHeader2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(filterNameLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(includeDefaultFilterCheckbox)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(newFilterRuleButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(deleteFilterRuleButton)
            .addContainerGap(149, Short.MAX_VALUE))
          .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void newFilterButtonActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_newFilterButtonActionPerformed
  {//GEN-HEADEREND:event_newFilterButtonActionPerformed
 
  }//GEN-LAST:event_newFilterButtonActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JButton deleteFilterButton;
  protected javax.swing.JButton deleteFilterRuleButton;
  protected org.jmeld.ui.swing.DetailHeader detailHeader1;
  protected org.jmeld.ui.swing.DetailHeader detailHeader2;
  protected javax.swing.JLabel filterNameLabel;
  protected org.jmeld.ui.swing.table.JMTable filterRuleTable;
  protected org.jmeld.ui.swing.table.JMTable filterTable;
  protected org.jmeld.ui.swing.GradientLabel gradientLabel1;
  protected javax.swing.JCheckBox includeDefaultFilterCheckbox;
  public org.jmeld.ui.swing.table.JMTable jMTable1;
  public javax.swing.JScrollPane jScrollPane1;
  public javax.swing.JScrollPane jScrollPane2;
  public javax.swing.JScrollPane jScrollPane3;
  protected javax.swing.JButton newFilterButton;
  protected javax.swing.JButton newFilterRuleButton;
  // End of variables declaration//GEN-END:variables
  
}
