/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IgnoreSettingsForm.java
 *
 * Created on Sep 13, 2008, 8:11:18 PM
 */

package org.jmeld.ui.settings;

/**
 *
 * @author kees
 */
public class IgnoreSettingsForm extends javax.swing.JPanel {

    /** Creates new form IgnoreSettingsForm */
    public IgnoreSettingsForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    detailHeader4 = new org.jmeld.ui.swing.DetailHeader();
    ignoreWhitespaceAtBeginCheckBox = new javax.swing.JCheckBox();
    ignoreWhitespaceInBetweenCheckBox = new javax.swing.JCheckBox();
    ignoreWhitespaceAtEndCheckBox = new javax.swing.JCheckBox();
    ignoreEOLCheckBox = new javax.swing.JCheckBox();
    ignoreBlankLinesCheckBox = new javax.swing.JCheckBox();
    ignoreCaseCheckBox = new javax.swing.JCheckBox();

    detailHeader4.setText("Ignore ");

    ignoreWhitespaceAtBeginCheckBox.setText("Ignore whitespace at the begin of a line");
    ignoreWhitespaceAtBeginCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ignoreWhitespaceAtBeginCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

    ignoreWhitespaceInBetweenCheckBox.setText("Ignore whitespace between begin and end of a line");
    ignoreWhitespaceInBetweenCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ignoreWhitespaceInBetweenCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

    ignoreWhitespaceAtEndCheckBox.setText("Ignore whitespace at the end of a line");
    ignoreWhitespaceAtEndCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ignoreWhitespaceAtEndCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

    ignoreEOLCheckBox.setText("Ignore EOL (End of line markers)");
    ignoreEOLCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ignoreEOLCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

    ignoreBlankLinesCheckBox.setText("Ignore blank lines");
    ignoreBlankLinesCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ignoreBlankLinesCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

    ignoreCaseCheckBox.setText("Ignore case");
    ignoreCaseCheckBox.setBorder(null);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(detailHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(ignoreEOLCheckBox)
              .addComponent(ignoreWhitespaceAtBeginCheckBox)
              .addComponent(ignoreBlankLinesCheckBox)
              .addComponent(ignoreCaseCheckBox)
              .addComponent(ignoreWhitespaceInBetweenCheckBox)
              .addComponent(ignoreWhitespaceAtEndCheckBox))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(detailHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ignoreWhitespaceAtBeginCheckBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ignoreWhitespaceInBetweenCheckBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ignoreWhitespaceAtEndCheckBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ignoreEOLCheckBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ignoreBlankLinesCheckBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ignoreCaseCheckBox)
        .addContainerGap(16, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.jmeld.ui.swing.DetailHeader detailHeader4;
  protected javax.swing.JCheckBox ignoreBlankLinesCheckBox;
  protected javax.swing.JCheckBox ignoreCaseCheckBox;
  protected javax.swing.JCheckBox ignoreEOLCheckBox;
  protected javax.swing.JCheckBox ignoreWhitespaceAtBeginCheckBox;
  protected javax.swing.JCheckBox ignoreWhitespaceAtEndCheckBox;
  protected javax.swing.JCheckBox ignoreWhitespaceInBetweenCheckBox;
  // End of variables declaration//GEN-END:variables

}
