/*
 * SettingsPanel2.java
 *
 * Created on January 19, 2007, 8:02 PM
 */

package org.jmeld.ui.settings;

import java.awt.CardLayout;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JList;
import org.jmeld.ui.AbstractContentPanel;
import org.jmeld.ui.util.ImageUtil;

/**
 *
 * @author  kees
 */
public class SettingsPanelForm extends AbstractContentPanel
{
  
  /** Creates new form SettingsPanel2 */
  public SettingsPanelForm ()
  {
    initComponents ();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    saveButton = new javax.swing.JButton();
    saveAsButton = new javax.swing.JButton();
    reloadButton = new javax.swing.JButton();
    fileLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    settingItems = new javax.swing.JList();
    settingsPanel = new javax.swing.JPanel();

    saveButton.setText("save");

    saveAsButton.setText("saveAs");

    reloadButton.setText("reLoad");

    fileLabel.setText("jLabel1");

    settingItems.setModel(new javax.swing.AbstractListModel()
    {
      String[] strings = { "MyEditor", "MyFilter" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(settingItems);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(settingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(saveButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(reloadButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(saveAsButton)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(saveButton)
          .addComponent(saveAsButton)
          .addComponent(reloadButton)
          .addComponent(fileLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
          .addComponent(settingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JLabel fileLabel;
  protected javax.swing.JScrollPane jScrollPane1;
  protected javax.swing.JButton reloadButton;
  protected javax.swing.JButton saveAsButton;
  protected javax.swing.JButton saveButton;
  protected javax.swing.JList settingItems;
  protected javax.swing.JPanel settingsPanel;
  // End of variables declaration//GEN-END:variables


}
