/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommitForm.java
 *
 * Created on Sep 20, 2008, 3:01:18 PM
 */

package org.jmeld.ui.vc;

/**
 *
 * @author kees
 */
public class CommitForm extends javax.swing.JPanel {

    /** Creates new form CommitForm */
    public CommitForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    commitTextPane = new javax.swing.JTextPane();
    executeButton = new javax.swing.JButton();

    commitTextPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    executeButton.setText("CO");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(commitTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(commitTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JTextPane commitTextPane;
  public javax.swing.JButton executeButton;
  // End of variables declaration//GEN-END:variables

}
