/*
 * EditorPreferencePanel.java
 *
 * Created on January 10, 2007, 6:31 PM
 */

package org.jmeld.ui.conf;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import org.jmeld.conf.EditorConfiguration;
import org.jmeld.conf.JMeldSettings;
import org.jmeld.ui.util.EmptyIcon;
import org.jmeld.util.conf.ConfigurationListenerIF;

/**
 *
 * @author  kees
 */
public class EditorPreferencePanel extends javax.swing.JPanel
    implements ConfigurationListenerIF
{
  static private JDialog       colorDialog;
  static private JColorChooser colorChooser;
  
  /** Creates new form EditorPreferencePanel */
  public EditorPreferencePanel ()
  {
    initComponents ();
    updateFromConfiguration();
    JMeldSettings.getInstance().addConfigurationListener(this);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    buttonGroup1 = new javax.swing.ButtonGroup();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jLabel3 = new javax.swing.JLabel();
    tabSizeSpinner = new javax.swing.JSpinner();
    showLineNumbersCheckBox = new javax.swing.JCheckBox();
    detailHeader1 = new org.jmeld.ui.swing.DetailHeader();
    detailHeader2 = new org.jmeld.ui.swing.DetailHeader();
    detailHeader3 = new org.jmeld.ui.swing.DetailHeader();
    colorAddedButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    colorDeletedButton = new javax.swing.JButton();
    colorChangedButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    restoreOriginalColorsButton = new javax.swing.JButton();
    gradientLabel1 = new org.jmeld.ui.swing.GradientLabel();

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("Use default font");
    jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("Use custom font");
    jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

    jLabel3.setText("Tab size");

    tabSizeSpinner.addChangeListener(new javax.swing.event.ChangeListener()
    {
      public void stateChanged(javax.swing.event.ChangeEvent evt)
      {
        tabSizeSpinnerStateChanged(evt);
      }
    });

    showLineNumbersCheckBox.setText("Show line numbers");
    showLineNumbersCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    showLineNumbersCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
    showLineNumbersCheckBox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        showLineNumbersCheckBoxActionPerformed(evt);
      }
    });

    detailHeader1.setText("Font");

    detailHeader2.setText("Miscellaneous");

    detailHeader3.setText("Colors");

    colorAddedButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    colorAddedButton.setFocusable(false);
    colorAddedButton.setPreferredSize(new java.awt.Dimension(20, 20));
    colorAddedButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        colorAddedButtonActionPerformed(evt);
      }
    });

    jLabel1.setText("Chunk of code has been added");

    colorDeletedButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    colorDeletedButton.setFocusable(false);
    colorDeletedButton.setPreferredSize(new java.awt.Dimension(20, 20));
    colorDeletedButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        colorDeletedButtonActionPerformed(evt);
      }
    });

    colorChangedButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    colorChangedButton.setFocusable(false);
    colorChangedButton.setPreferredSize(new java.awt.Dimension(20, 20));
    colorChangedButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        colorChangedButtonActionPerformed(evt);
      }
    });

    jLabel2.setText("Chunk of code has been deleted");

    jLabel4.setText("Chunk of code has changed");

    restoreOriginalColorsButton.setText("Restore original colors");
    restoreOriginalColorsButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        RestoreColors(evt);
      }
    });

    gradientLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    gradientLabel1.setText("Editor settings");
    gradientLabel1.setFont(new java.awt.Font("Dialog", 1, 18));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(showLineNumbersCheckBox)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tabSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
              .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(colorDeletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(colorAddedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(colorChangedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel2)
                      .addComponent(jLabel1)
                      .addComponent(jLabel4))
                    .addGap(143, 143, 143))
                  .addComponent(restoreOriginalColorsButton)))
              .addComponent(gradientLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
            .addGap(143, 143, 143))
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(detailHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jRadioButton2)
                  .addComponent(jRadioButton1)))
              .addComponent(detailHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(detailHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(399, 399, 399))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(gradientLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(detailHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton2)
        .addGap(15, 15, 15)
        .addComponent(detailHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(tabSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(showLineNumbersCheckBox)
        .addGap(16, 16, 16)
        .addComponent(detailHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(colorAddedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(colorDeletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(colorChangedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(restoreOriginalColorsButton)
        .addGap(100, 100, 100))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void colorChangedButtonActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_colorChangedButtonActionPerformed
  {//GEN-HEADEREND:event_colorChangedButtonActionPerformed
     Color color;
     
     color = chooseColor(getEditorSettings().getChangedColor());
     if(color != null)
     {
       getEditorSettings().setChangedColor(color);
     }
  }//GEN-LAST:event_colorChangedButtonActionPerformed

  private void colorDeletedButtonActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_colorDeletedButtonActionPerformed
  {//GEN-HEADEREND:event_colorDeletedButtonActionPerformed
     Color color;
     
     color = chooseColor(getEditorSettings().getDeletedColor());
     if(color != null)
     {
       getEditorSettings().setDeletedColor(color);
     }
  }//GEN-LAST:event_colorDeletedButtonActionPerformed

  private void RestoreColors (java.awt.event.ActionEvent evt)//GEN-FIRST:event_RestoreColors
  {//GEN-HEADEREND:event_RestoreColors
    getEditorSettings().restoreColors();
  }//GEN-LAST:event_RestoreColors

  private void colorAddedButtonActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_colorAddedButtonActionPerformed
  {//GEN-HEADEREND:event_colorAddedButtonActionPerformed
     Color color;
     
     color = chooseColor(getEditorSettings().getAddedColor());
     if(color != null)
     {
       getEditorSettings().setAddedColor(color);
     }
  }//GEN-LAST:event_colorAddedButtonActionPerformed

  private void tabSizeSpinnerStateChanged (javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_tabSizeSpinnerStateChanged
  {//GEN-HEADEREND:event_tabSizeSpinnerStateChanged
     getEditorSettings().setTabSize((Integer) tabSizeSpinner.getValue());
  }//GEN-LAST:event_tabSizeSpinnerStateChanged

  private void showLineNumbersCheckBoxActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_showLineNumbersCheckBoxActionPerformed
  {//GEN-HEADEREND:event_showLineNumbersCheckBoxActionPerformed
     getEditorSettings().setShowLineNumbers(showLineNumbersCheckBox.isSelected ());
  }//GEN-LAST:event_showLineNumbersCheckBoxActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton colorAddedButton;
  private javax.swing.JButton colorChangedButton;
  private javax.swing.JButton colorDeletedButton;
  private org.jmeld.ui.swing.DetailHeader detailHeader1;
  private org.jmeld.ui.swing.DetailHeader detailHeader2;
  private org.jmeld.ui.swing.DetailHeader detailHeader3;
  private org.jmeld.ui.swing.GradientLabel gradientLabel1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JButton restoreOriginalColorsButton;
  private javax.swing.JCheckBox showLineNumbersCheckBox;
  private javax.swing.JSpinner tabSizeSpinner;
  // End of variables declaration//GEN-END:variables

  private Color chooseColor(Color initialColor)
  { 
    // Do not instantiate ColorChooser multiple times because it contains
    //   a memory leak.
    if(colorDialog == null)
    {
      colorChooser = new JColorChooser(initialColor);
      colorDialog = colorChooser.createDialog(null, "Choose color", true, 
                                    colorChooser, null, null);
    }

    colorChooser.setColor(initialColor);
    colorDialog.setVisible(true);

    return colorChooser.getColor();
  }

  private void updateFromConfiguration()
  {
    EditorConfiguration settings;

    settings = getEditorSettings();
    colorAddedButton.setIcon(new EmptyIcon(settings.getAddedColor(), 20, 20));
    colorDeletedButton.setIcon(new EmptyIcon(settings.getDeletedColor(), 20, 20));
    colorChangedButton.setIcon(new EmptyIcon(settings.getChangedColor(), 20, 20));
    //colorDeletedButton.setBackground(settings.getDeletedColor());
    //colorChangedButton.setBackground(settings.getChangedColor());
    showLineNumbersCheckBox.setSelected(settings.getShowLineNumbers());
    tabSizeSpinner.setValue(settings.getTabSize());
  }

  public void configurationChanged()
  {
    updateFromConfiguration();
  }

  private EditorConfiguration getEditorSettings()
  {
    return JMeldSettings.getInstance().getEditor();
  }
}
