/*
 * FolderDiffForm.java
 *
 * Created on January 28, 2007, 11:17 AM
 */

package org.jmeld.ui;

/**
 *
 * @author  kees
 */
public class FolderDiffForm extends AbstractContentPanel
{
  
  /** Creates new form FolderDiffForm */
  public FolderDiffForm ()
  {
    initComponents ();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    folder1Label = new org.jmeld.ui.swing.DiffLabel();
    folderBar = new javax.swing.JLabel();
    folder2Label = new org.jmeld.ui.swing.DiffLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    folderTreeTable = new org.jmeld.ui.swing.table.JMTreeTable();

    folder1Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    folderBar.setText("jLabel2");

    folder2Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jScrollPane1.setViewportView(folderTreeTable);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addContainerGap())
          .add(layout.createSequentialGroup()
            .add(folder1Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(folder2Label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addContainerGap())
          .add(layout.createSequentialGroup()
            .add(folderBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .add(208, 208, 208))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(folder1Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(folder2Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(folderBar)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected org.jmeld.ui.swing.DiffLabel folder1Label;
  protected org.jmeld.ui.swing.DiffLabel folder2Label;
  protected javax.swing.JLabel folderBar;
  protected org.jmeld.ui.swing.table.JMTreeTable folderTreeTable;
  protected javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
  
}
