/*
 * NewPanelDialogForm.java
 *
 * Created on August 28, 2007, 9:10 PM
 */

package org.jmeld.ui;

/**
 *
 * @author  kees
 */
public class NewPanelDialogForm extends javax.swing.JPanel {
    
    /** Creates new form NewPanelDialogForm */
    public NewPanelDialogForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    fileLeftLabel = new javax.swing.JLabel();
    fileRightLabel = new javax.swing.JLabel();
    fileBrowseLeftButton = new javax.swing.JButton();
    fileBrowseRightButton = new javax.swing.JButton();
    fileLeftComboBox = new javax.swing.JComboBox();
    fileRightComboBox = new javax.swing.JComboBox();
    fileFilterComboBox = new javax.swing.JComboBox();
    fileLeftReadonlyCheckBox = new javax.swing.JCheckBox();
    fileRightReadonlyCheckBox = new javax.swing.JCheckBox();
    filterLabel = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jComboBox3 = new javax.swing.JComboBox();
    jComboBox4 = new javax.swing.JComboBox();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jCheckBox1 = new javax.swing.JCheckBox();
    jCheckBox2 = new javax.swing.JCheckBox();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    fileLeftLabel.setFont(new java.awt.Font("Dialog", 1, 11));
    fileLeftLabel.setText("Left");

    fileRightLabel.setFont(new java.awt.Font("Dialog", 1, 11));
    fileRightLabel.setText("Right");

    fileBrowseLeftButton.setText("Browse");

    fileBrowseRightButton.setText("Browse");

    fileLeftComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    fileRightComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    fileFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    fileLeftReadonlyCheckBox.setText("Left readonly");

    fileRightReadonlyCheckBox.setText("Right readonly");

    filterLabel.setFont(new java.awt.Font("Dialog", 1, 11));
    filterLabel.setText("Filter");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fileRightLabel)
              .addComponent(fileLeftLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fileRightComboBox, 0, 261, Short.MAX_VALUE)
              .addComponent(fileLeftComboBox, 0, 261, Short.MAX_VALUE)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(filterLabel)
            .addGap(11, 11, 11)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fileLeftReadonlyCheckBox)
              .addComponent(fileFilterComboBox, 0, 263, Short.MAX_VALUE)
              .addComponent(fileRightReadonlyCheckBox))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(fileBrowseRightButton)
          .addComponent(fileBrowseLeftButton))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(fileLeftLabel)
          .addComponent(fileLeftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fileBrowseLeftButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(fileRightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fileRightLabel)
          .addComponent(fileBrowseRightButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(fileFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(filterLabel))
        .addGap(18, 18, 18)
        .addComponent(fileLeftReadonlyCheckBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fileRightReadonlyCheckBox)
        .addContainerGap(57, Short.MAX_VALUE))
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fileFilterComboBox, fileLeftComboBox, fileRightComboBox});

    jTabbedPane1.addTab("File comparison", jPanel1);

    jLabel3.setText("Left");

    jLabel4.setText("Right");

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jButton5.setText("Browse");

    jButton6.setText("Browse");

    jCheckBox1.setText("Left readonly");

    jCheckBox2.setText("Right readonly");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jCheckBox2)
          .addComponent(jCheckBox1)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.TRAILING, 0, 263, Short.MAX_VALUE)
              .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, 263, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jButton5)
          .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jButton6)
          .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jCheckBox1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckBox2)
        .addContainerGap(86, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Directory comparison", jPanel2);

    jButton1.setText("Cancel");

    jButton2.setText("OK");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(124, 124, 124)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        .addGap(12, 12, 12)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton2))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
    
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JButton fileBrowseLeftButton;
  protected javax.swing.JButton fileBrowseRightButton;
  protected javax.swing.JComboBox fileFilterComboBox;
  protected javax.swing.JComboBox fileLeftComboBox;
  protected javax.swing.JLabel fileLeftLabel;
  protected javax.swing.JCheckBox fileLeftReadonlyCheckBox;
  protected javax.swing.JComboBox fileRightComboBox;
  protected javax.swing.JLabel fileRightLabel;
  protected javax.swing.JCheckBox fileRightReadonlyCheckBox;
  protected javax.swing.JLabel filterLabel;
  protected javax.swing.JButton jButton1;
  protected javax.swing.JButton jButton2;
  protected javax.swing.JButton jButton5;
  protected javax.swing.JButton jButton6;
  protected javax.swing.JCheckBox jCheckBox1;
  protected javax.swing.JCheckBox jCheckBox2;
  protected javax.swing.JComboBox jComboBox3;
  protected javax.swing.JComboBox jComboBox4;
  protected javax.swing.JLabel jLabel3;
  protected javax.swing.JLabel jLabel4;
  protected javax.swing.JPanel jPanel1;
  protected javax.swing.JPanel jPanel2;
  protected javax.swing.JTabbedPane jTabbedPane1;
  // End of variables declaration//GEN-END:variables
    
}
