/*
 * SaveSettingsPanel.java
 *
 * Created on September 14, 2007, 6:32 PM
 */

package org.jmeld.ui;

/**
 *
 * @author  kees
 */
public class SaveSettingsPanel
    extends javax.swing.JPanel
{

  /** Creates new form SaveSettingsPanel */
  public SaveSettingsPanel()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    jLabel1.setFont(jLabel1.getFont().deriveFont(
      jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
    jLabel1.setText("Settings have changed");

    jLabel2.setFont(jLabel2.getFont().deriveFont(
      jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
    jLabel2.setText("Would you like to save the settings?");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
        this);
    this.setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(
      org.jdesktop.layout.GroupLayout.LEADING).add(
      layout.createSequentialGroup().addContainerGap().add(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1).add(jLabel2)).addContainerGap(
        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(
      org.jdesktop.layout.GroupLayout.LEADING).add(
      layout.createSequentialGroup().addContainerGap().add(jLabel1)
          .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
          .add(jLabel2).addContainerGap(13, Short.MAX_VALUE)));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JLabel jLabel1;
  protected javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables

}
